include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    unnecessary_const: true
    unnecessary_new: true
    avoid_print: true
    prefer_single_quotes: false
    use_key_in_widget_constructors: true

